language: ruby

rvm:
 - 2.5

sudo: required

services:
  - docker

before_install:
  - docker build --tag movii/react-test --file ${TRAVIS_BUILD_DIR}/client/Dockerfile.dev ${TRAVIS_BUILD_DIR}/client

script:
  - docker run movii/react-test npm run test -- --coverage

after_success:
  # After (all) test successfully past,
  # build our images
  - docker build -t movii/docker-deplyment-complex-client ./client
  - docker build -t movii/docker-deplyment-complex-nginx ./nginx
  - docker build -t movii/docker-deplyment-complex-server ./server
  - docker build -t movii/docker-deplyment-complex-worker ./worker
  # Login in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push movii/docker-deplyment-complex-client
  - docker push movii/docker-deplyment-complex-nginx
  - docker push movii/docker-deplyment-complex-server
  - docker push movii/docker-deplyment-complex-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: docker-multi-service
  env: DockerMultiService-env
  bucket_name: "elasticbeanstalk-ap-northeast-1-164521457965"
  bucket_path: "docker-deployment-multi-services"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
